before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X github.com/noborus/jpug-doc-tool/cmd/jpugdoc.Version={{.Version}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^doc:'
      - '^test:'
brews:
  -
    name: jpug-doc-tool
    repository:
      owner: noborus
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: noborus
      email: noborusai@gmail.com
    homepage: https://github.com/noborus/jpug-doc-tool
    description: "jpug-doc tool"
    test:
      system "#{bin}/jpug-doc-tool --version"
    install:
      bin.install "jpug-doc-tool"